name: Build Docker Image

on:
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Yarn build
      uses: Numih/act-yarn-build@v1
    
    - name: Docker build deploy
      uses: Numih/act-docker-build-deploy-image@v1
      with:
        dockerfile: docker/Dockerfile
        user: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
