name: Deploy maven package

on:
  release:
    types: [ released, prereleased ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy maven package
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      - id: setup
        name: Create settings.xml
        uses: Numih/act-maven-settings-setup@v1
        with:
          url: ${{ secrets.MAVEN_REPOSITORY_URL }}
          user: ${{ secrets.MAVEN_REPOSITORY_USER  }}
          password: ${{ secrets.MAVEN_REPOSITORY_PASSWORD  }}
      - id: deploy
        name: Deploy package
        run: mvn clean deploy
